name: Fazer deploy aplicação vue
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Publicando a aplicação
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v1
      - name: Criar ambiente do node
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Instalar dependências e executar o script de build
        run: |
          npm install i
          npm run build
      - name: Publicando o build gerado
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: master
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}